/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.schema.registry.domain;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SchemaResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6844928237071278457L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SchemaResponse\",\"namespace\":\"com.example.schema.registry.domain\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"subject\",\"type\":\"string\"},{\"name\":\"format\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"int\"},{\"name\":\"definition\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SchemaResponse> ENCODER =
      new BinaryMessageEncoder<SchemaResponse>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SchemaResponse> DECODER =
      new BinaryMessageDecoder<SchemaResponse>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SchemaResponse> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SchemaResponse> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SchemaResponse> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SchemaResponse>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SchemaResponse to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SchemaResponse from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SchemaResponse instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SchemaResponse fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int id;
   private java.lang.CharSequence subject;
   private java.lang.CharSequence format;
   private int version;
   private java.lang.CharSequence definition;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SchemaResponse() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param subject The new value for subject
   * @param format The new value for format
   * @param version The new value for version
   * @param definition The new value for definition
   */
  public SchemaResponse(java.lang.Integer id, java.lang.CharSequence subject, java.lang.CharSequence format, java.lang.Integer version, java.lang.CharSequence definition) {
    this.id = id;
    this.subject = subject;
    this.format = format;
    this.version = version;
    this.definition = definition;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return subject;
    case 2: return format;
    case 3: return version;
    case 4: return definition;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: subject = (java.lang.CharSequence)value$; break;
    case 2: format = (java.lang.CharSequence)value$; break;
    case 3: version = (java.lang.Integer)value$; break;
    case 4: definition = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'subject' field.
   * @return The value of the 'subject' field.
   */
  public java.lang.CharSequence getSubject() {
    return subject;
  }


  /**
   * Sets the value of the 'subject' field.
   * @param value the value to set.
   */
  public void setSubject(java.lang.CharSequence value) {
    this.subject = value;
  }

  /**
   * Gets the value of the 'format' field.
   * @return The value of the 'format' field.
   */
  public java.lang.CharSequence getFormat() {
    return format;
  }


  /**
   * Sets the value of the 'format' field.
   * @param value the value to set.
   */
  public void setFormat(java.lang.CharSequence value) {
    this.format = value;
  }

  /**
   * Gets the value of the 'version' field.
   * @return The value of the 'version' field.
   */
  public int getVersion() {
    return version;
  }


  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(int value) {
    this.version = value;
  }

  /**
   * Gets the value of the 'definition' field.
   * @return The value of the 'definition' field.
   */
  public java.lang.CharSequence getDefinition() {
    return definition;
  }


  /**
   * Sets the value of the 'definition' field.
   * @param value the value to set.
   */
  public void setDefinition(java.lang.CharSequence value) {
    this.definition = value;
  }

  /**
   * Creates a new SchemaResponse RecordBuilder.
   * @return A new SchemaResponse RecordBuilder
   */
  public static com.example.schema.registry.domain.SchemaResponse.Builder newBuilder() {
    return new com.example.schema.registry.domain.SchemaResponse.Builder();
  }

  /**
   * Creates a new SchemaResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SchemaResponse RecordBuilder
   */
  public static com.example.schema.registry.domain.SchemaResponse.Builder newBuilder(com.example.schema.registry.domain.SchemaResponse.Builder other) {
    if (other == null) {
      return new com.example.schema.registry.domain.SchemaResponse.Builder();
    } else {
      return new com.example.schema.registry.domain.SchemaResponse.Builder(other);
    }
  }

  /**
   * Creates a new SchemaResponse RecordBuilder by copying an existing SchemaResponse instance.
   * @param other The existing instance to copy.
   * @return A new SchemaResponse RecordBuilder
   */
  public static com.example.schema.registry.domain.SchemaResponse.Builder newBuilder(com.example.schema.registry.domain.SchemaResponse other) {
    if (other == null) {
      return new com.example.schema.registry.domain.SchemaResponse.Builder();
    } else {
      return new com.example.schema.registry.domain.SchemaResponse.Builder(other);
    }
  }

  /**
   * RecordBuilder for SchemaResponse instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SchemaResponse>
    implements org.apache.avro.data.RecordBuilder<SchemaResponse> {

    private int id;
    private java.lang.CharSequence subject;
    private java.lang.CharSequence format;
    private int version;
    private java.lang.CharSequence definition;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.schema.registry.domain.SchemaResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.subject)) {
        this.subject = data().deepCopy(fields()[1].schema(), other.subject);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.format)) {
        this.format = data().deepCopy(fields()[2].schema(), other.format);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.version)) {
        this.version = data().deepCopy(fields()[3].schema(), other.version);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.definition)) {
        this.definition = data().deepCopy(fields()[4].schema(), other.definition);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing SchemaResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.schema.registry.domain.SchemaResponse other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.subject)) {
        this.subject = data().deepCopy(fields()[1].schema(), other.subject);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.format)) {
        this.format = data().deepCopy(fields()[2].schema(), other.format);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.version)) {
        this.version = data().deepCopy(fields()[3].schema(), other.version);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.definition)) {
        this.definition = data().deepCopy(fields()[4].schema(), other.definition);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.schema.registry.domain.SchemaResponse.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.example.schema.registry.domain.SchemaResponse.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'subject' field.
      * @return The value.
      */
    public java.lang.CharSequence getSubject() {
      return subject;
    }


    /**
      * Sets the value of the 'subject' field.
      * @param value The value of 'subject'.
      * @return This builder.
      */
    public com.example.schema.registry.domain.SchemaResponse.Builder setSubject(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.subject = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'subject' field has been set.
      * @return True if the 'subject' field has been set, false otherwise.
      */
    public boolean hasSubject() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'subject' field.
      * @return This builder.
      */
    public com.example.schema.registry.domain.SchemaResponse.Builder clearSubject() {
      subject = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'format' field.
      * @return The value.
      */
    public java.lang.CharSequence getFormat() {
      return format;
    }


    /**
      * Sets the value of the 'format' field.
      * @param value The value of 'format'.
      * @return This builder.
      */
    public com.example.schema.registry.domain.SchemaResponse.Builder setFormat(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.format = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'format' field has been set.
      * @return True if the 'format' field has been set, false otherwise.
      */
    public boolean hasFormat() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'format' field.
      * @return This builder.
      */
    public com.example.schema.registry.domain.SchemaResponse.Builder clearFormat() {
      format = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * @return The value.
      */
    public int getVersion() {
      return version;
    }


    /**
      * Sets the value of the 'version' field.
      * @param value The value of 'version'.
      * @return This builder.
      */
    public com.example.schema.registry.domain.SchemaResponse.Builder setVersion(int value) {
      validate(fields()[3], value);
      this.version = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'version' field.
      * @return This builder.
      */
    public com.example.schema.registry.domain.SchemaResponse.Builder clearVersion() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'definition' field.
      * @return The value.
      */
    public java.lang.CharSequence getDefinition() {
      return definition;
    }


    /**
      * Sets the value of the 'definition' field.
      * @param value The value of 'definition'.
      * @return This builder.
      */
    public com.example.schema.registry.domain.SchemaResponse.Builder setDefinition(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.definition = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'definition' field has been set.
      * @return True if the 'definition' field has been set, false otherwise.
      */
    public boolean hasDefinition() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'definition' field.
      * @return This builder.
      */
    public com.example.schema.registry.domain.SchemaResponse.Builder clearDefinition() {
      definition = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SchemaResponse build() {
      try {
        SchemaResponse record = new SchemaResponse();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.subject = fieldSetFlags()[1] ? this.subject : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.format = fieldSetFlags()[2] ? this.format : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.version = fieldSetFlags()[3] ? this.version : (java.lang.Integer) defaultValue(fields()[3]);
        record.definition = fieldSetFlags()[4] ? this.definition : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SchemaResponse>
    WRITER$ = (org.apache.avro.io.DatumWriter<SchemaResponse>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SchemaResponse>
    READER$ = (org.apache.avro.io.DatumReader<SchemaResponse>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

    out.writeString(this.subject);

    out.writeString(this.format);

    out.writeInt(this.version);

    out.writeString(this.definition);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

      this.subject = in.readString(this.subject instanceof Utf8 ? (Utf8)this.subject : null);

      this.format = in.readString(this.format instanceof Utf8 ? (Utf8)this.format : null);

      this.version = in.readInt();

      this.definition = in.readString(this.definition instanceof Utf8 ? (Utf8)this.definition : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        case 1:
          this.subject = in.readString(this.subject instanceof Utf8 ? (Utf8)this.subject : null);
          break;

        case 2:
          this.format = in.readString(this.format instanceof Utf8 ? (Utf8)this.format : null);
          break;

        case 3:
          this.version = in.readInt();
          break;

        case 4:
          this.definition = in.readString(this.definition instanceof Utf8 ? (Utf8)this.definition : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










